# Generated by Django 5.0.2 on 2024-02-16 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_b', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myusermodel',
            managers=[
            ],
        ),
    ]
